### ISSUE TITLE
Components do not "adhere to WCAG accessibility guidelines"

### ISSUE THREAD

**Issue by gtibrett** [functional-ui/functional-ui-kit#7]
Playing with your docs and adding a label to the example generates this React code
```
<FuiTextInput
  label="label"
  onChange={function noRefCheck(){}}
  placeholder="Placeholder"
  value=""
/>
```

which is rendered as divs with no association between the label an field nor even a role of label for the div that contains the label
```
<div class="fui-text-input-wrapper undefined">
   <div class="fui-text-input-label">label</div>
   <div class="fui-text-input-container ">  
      <div class="fui-text-input-input-container fui-interactable">
         <input type="text" placeholder="Placeholder" class="fui-text-input-input" value="">
      </div>
   </div>
</div>
```

also worth noting that the default example uses placeholder instead of a label.

None of this adheres to WCAG guidelines nor do any of the form components.

**Comment by alexyakir** [comment]
Thanks for catching this 🙏
We addressed these issues

**Comment by gtibrett** [comment]
Added some comments to the referenced commit. Not sure I would consider this completely resolved. It is certainly a good step in the right direction tho.  Thanks for working on this quickly.  Happy to collaborate if you need more info.
