### ISSUE TITLE
Intermediate checkboxes mis-naming.

### ISSUE THREAD

**Issue by parkersweb** [functional-ui/functional-ui-kit#8]
Hey there :wave:

Looking through this for the first time - so much good stuff to see here! Just wanted to flag up a mis-naming - the boolean property for when the checkbox is neither checked or unchecked should be "indeterminate" not "intermediate". See: https://css-tricks.com/indeterminate-checkboxes/

**Comment by alexyakir** [comment]
thanks for catching this @parkersweb 🙏
